theme: jekyll-theme-slate
title: Notas
collections:
    posts:
        title: Posts
    books:
        title: Libros
        output: true
    reflections:
        title: Reflexiones
        output: true
    tributes:
        title: Homenajes
        output: true
    films:
        title: Películas
        output: true
