theme: jekyll-theme-slate
title: NOTAS
collections:
    posts:
        title: Posts
    books:
        title: Libros
        output: true
    reflections:
        title: Reflexiones
        output: true
    tributes:
        title: Homenajes
        output: true
